version: '3'

services:
  mongo:
    image: mongo:5.0.26
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - acorn-network

  acorn-clicker:
    image: acorn-clicker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - acorn-network

networks:
  acorn-network:
